### ISSUE TITLE
Falsche TAB-Reihenfolge

### ISSUE THREAD

**Issue by BluditNet** [Jean28518/invoice-creator-german#12]
Die logische Reihenfolge der Felder, zu denen mit der TAB-Taste gesprungen wird, ist falsch.
Beispiel:
Nach Eingabe des Namens wird zur Artikelbeschreibung gesprungen und nicht zur Straße.

PS: Ich mag euren YouTube-Kanal

**Comment by Jean28518** [comment]
Danke für Deinen Hinweis!
Werden wir in den nächsten Versionen fixen

**Comment by Jean28518** [comment]
Done :)
