### ISSUE TITLE
Name misaligns Content

### ISSUE THREAD

**Issue by Timeox2k** [Jean28518/invoice-creator-german#21]
When you enter your name as "Max Mustermann" and your email as "max.mustermann@example.com", the details are displayed correctly as follows:

```
Name: Max Mustermann
Email: max.mustermann@example.com
Tel: -
```

However, if your name is "Max Mustermann" and you're from the company "Mustermann GmbH", and you enter your name as "Max Mustermann // Mustermann GmbH", the name field is too long. As a result, the display becomes misaligned:

```
Name: Max Mustermann // Must
           ermann GmbH
Email:
  max.mustermann@example.com
Tel:
   -
```

This issue occurs because, as I guess, the name field is not able to accommodate the entire input if it exceeds a certain length, causing the text to wrap onto the next line and disrupt the alignment of the subsequent fields. This could potentially lead to confusion and misinterpretation of the displayed information. A potential solution could be to increase the width of the name field or implement a character limit for the input. This would ensure that the display remains consistent and clear, regardless of the length of the input.

**Comment by Jean28518** [comment]
Thanks for your issue!
I guess we will solve this by adding another Field for the company.
It would be to much effort to find a good solution for your problem otherwise :)

**Comment by Jean28518** [comment]
I added a company field for the new version which will be released in a few days :)
