### ISSUE TITLE
Open the invoice folder if an invoice got created. (Only after the first creation in a session)

### ISSUE THREAD

**Issue by Palace4Software** [Jean28518/invoice-creator-german#5]
- [x] The "Vorschau" button do also not work [sometimes]
- [x] The "Speichern" button do also not work [sometimes]
- [x] Discount do not work (is written in the UI, but cannot found in the PDF)
- [ ] If the invoice was saved, the invoice-folder don't open.

If you start the program from the terminal, you will not get a error message.

**Comment by Jean28518** [comment]
The invoice folder doesn't open itself because if you generate multiple invoices that could be annoying. But I will work on another mechanism here.
The rest is done :)

**Comment by Jean28518** [comment]
At the newest version the folder opens everytime after a creation.
Good idea to just open a new window after specific time/only once per session

**Comment by actionschnitzel** [comment]
The tool is currently being tested in our company. I have received feedback from employees that it is very confusing that the file browser opens after the invoice has been created. 
It would make more sense if the .pdf file opened directly.

My suggestion would be to start the invoice with `xdg-open` `(xdg-open path/to/file.pdf`)

With regards

**Comment by Jean28518** [comment]
Thanks for your proposal!
This could be a setting: In my opinion its more helpful with the folder, because then you can drag and drop the invoice into you mail program :)
